### PR TITLE
vagrant: ovn-northd should use SSL when in SSL mode

### PR DESCRIPTION
**Pull request by girishmg**

### CODE REVIEW

**Comment by shettyg** [comment]
ovn-northd only needs to use SSL when DBs are not in the same host, correct? I think, we should not over-complicate the SSL documentation and usage. May be create a new doc for this specific use case.

**Comment by girishmg** [comment]
@shettyg I kind of agree with you here. I am going to split this PR into two commits. The first commit fixes the various documentation issues (i.e, not using self-signed instead using the CA and other things). 

In the second commit in a separate document will capture how to configure ovn-northd to use SSL. I will also change ovn-northd to use SSL for vagrant since it is easy to do and could serve as a reference implementation. 

Your thoughts?

**Comment by shettyg** [comment]
>I kind of agree with you here. I am going to split this PR into two commits. The first commit fixes the various documentation issues (i.e, not using self-signed instead using the CA and other things).

One of the reasons for using self-signed was to make documentation simpler. But, let me see how it looks without using self-signed and then decide whether the complication is worth it. So go ahead and send in the pull request and lets decide.

>In the second commit in a separate document will capture how to configure ovn-northd to use SSL. I will also change ovn-northd to use SSL for vagrant since it is easy to do and could serve as a reference implementation.

Lets leave vagrant from using it. For new people, it acts as a good place to start. Don't want to over complicate it.

**Comment by dcbw** [comment]
@shettyg needs a rebase?

**Comment by girishmg** [comment]
@dcbw I have done the rebase and @shettyg I have addressed your comments (have not included setting up ovn-northd for SSL in Vagrant)

**Pull request merged**
