### PR TITLE
vendor: Rebase to Kubernetes 1.7.

### PR DESCRIPTION
**Pull request by shettyg**
It looked very complex to indivdually fetch and update
packages using govendor to make the vendor directory compliant
with k8s 1.7.  The main complications are around how govendor
does a fetch from master branch of some dependent repositories.
Also, k8s apimachinary, client-go, apis etc look to have changes
where the versionining is quite poor. For e.g., it is hard to
know which version of apimachinary works with which version of
client-go repository.

It looks much easier to just copy the vendor directory from
a particular released kubernetes version.  In addition to
kubernetes, we have very less external dependencies.

This commit is a squash of the following steps:

1. Cleanup current vendor directory with a 'rm -rf'.
2. Copy k8s.io/vendor contents recursively to
our vendor directory.  This does get some code
which we don't need, but hopefully that is not a big deal
3. govendor init
4. govendor fetch github.com/openshift/origin/pkg/util/netutils
5. govendor fetch github.com/urfave/cli

This is enough to compile and basic pod creation and service creation
work fine.

Signed-off-by: Gurucharan Shetty <guru@ovn.org>

### CODE REVIEW

**Comment by shettyg** [comment]
@rajatchopra 

This is just a FYI to see if you have any comments.

**Comment by feiskyer** [comment]
> Copy k8s.io/vendor contents recursively to
> our vendor directory. This does get some code
> which we don't need, but hopefully that is not a big deal

A better way is download kubernetes release-1.7 branch and run `godep restore` inside kubernetes code. Then `govendor add +external` should work. After this, some vendors may still not exist, we could download and add it manually by `govendor add +external pkgname` or `govendor fetch`.

**Comment by shettyg** [comment]
@feiskyer 

Thanks! That was a good tip. It does reduce the code quite a bit. Though, one particular thing did not work, so I had to manually copy things.  The steps I did was:

1. Cleanup current vendor directory with a 'rm -rf'.
    2. From a downloaded source bundle of k8s 1.7.3, run
    'godep restore'
    3. From ovn-kubernetes/go-controller, run 'govendor init'
    4. govendor add +external
    5. The 'godep restore' does not restore the contents
    in k8s 1.7's staging directory. So those contents
    were manually copied to vendor directory of ovn-kubernetes repo
    6. govendor fetch github.com/openshift/origin/pkg/util/netutils
    7. govendor fetch github.com/urfave/cli

**Comment by shettyg** [comment]
I will close this and create a new pull request.

**Comment by rajatchopra** [comment]
We also need to do a 'govendor restore' in ovn-kubernetes/go-controller/ directory as the very first step.

Let's try and lock this process down. We may want to switch to 'dep' as the tool to use at some point if we find govendor is deficient in itself. e.g. govendor update does not seem to work as expected.

**Comment by shettyg** [comment]
'govendor restore' does not seem to exist (atleast in the version I am using). What is the purpose of the command?

**Comment by rajatchopra** [comment]
My bad. I assumed something like this exists as it does with 'godep restore'.

The purpose however is to have the dependencies restored in $GOPATH. And then we can update (git pull/rebase) the individual packages that we want to update. This becomes necessary if our vendor/ directory carries fixes/patches that are not upstream'ed yet. We don't patch anything right now of course.

Since govendor does not have this feature, we might want to switch at some point.

**Pull request closed without merging**
