### PR TITLE
vendor: Rebase to k8s 1.7.3

### PR DESCRIPTION
**Pull request by shettyg**
It looked very complex to indivdually fetch and update
packages using govendor to make the vendor directory compliant
with k8s 1.7. The main complications are around how govendor
does a fetch from master branch of some dependent repositories.
Also, k8s apimachinary, client-go, apis etc look to have changes
where the versionining is quite poor. For e.g., it is hard to
know which version of apimachinary works with which version of
client-go repository.

Instead, this commit does the following:

1. Cleanup current vendor directory with a 'rm -rf'.
2. From a downloaded source bundle of k8s 1.7.3, run
'godep restore'
3. From ovn-kubernetes/go-controller, run 'govendor init'
4. govendor add +external
5. The 'godep restore' does not restore the contents
in k8s 1.7's staging directory. So those contents
were manually copied to vendor directory of this repo.
6. govendor fetch github.com/openshift/origin/pkg/util/netutils
7. govendor fetch github.com/urfave/cli

Signed-off-by: Gurucharan Shetty <guru@ovn.org>

### CODE REVIEW

**Comment by shettyg** [comment]
@feiskyer @rajatchopra

**Comment by rajatchopra** [comment]
Looks good. I am still suspecting that there are extra files though. Got to figure how we can optimize this.

**Comment by shettyg** [comment]
I will try to do a 'govendor remove +u' optimization and recheck once I put the network policy code for initial feedback.

**Comment by feiskyer** [comment]
> The 'godep restore' does not restore the contents
> in k8s 1.7's staging directory. So those contents
> were manually copied to vendor directory of this repo.

Those imports could be got via `go get` and  added by `govendor add`, so that package versions could be kept in vendor.json.

All required but missing or external (in GOPATH but not in vendor) packages could be checked by `govendor list` command.

**Pull request merged**
