### PR TITLE
fix the wrong description of the installing process

### PR DESCRIPTION
**Pull request by chentao1596**
According to my test, i think it should be 'ovn-k8s-gateway-helper', thank you!

   Signed-off-by: chentao1596 <chen.tao3@zte.com.cn>

### CODE REVIEW

**Comment by shettyg** [comment]
Thanks. Can you give a Signed-off-by? For e.g:

Signed-off-by: Gurucharan Shetty \<guru@ovn.org\>

**Comment by chentao1596** [comment]
i added it, thank you!

**Comment by chentao1596** [comment]
change

**Comment by shettyg** [comment]
Thanks. Merged.

**Pull request merged**
