### PR TITLE
nicstobridge: Handle the case for /32 IP address.

### PR DESCRIPTION
**Pull request by shettyg**
One could set the IP address of a Linux interface as
    172.16.1.2/32 and then give it a default gateway of 172.16.1.1.
    This can be done for e.g. by running the following commands.
    
    1. ifconfig eth0 172.16.1.2 netmask 255.255.255.255 broadcast 172.16.1.2
    2. route add 172.16.1.1 dev eth0
    3. route add default gw 172.16.1.1
    
    The above configuration is what google cloud uses for its VMs.
    
    When the above configuration is used, the current code can fail
    because we may attenmpt to do 3. before 2. With this commit,
    we do 3. after everything else has been done.
    
    Fixes: #224
    Signed-off-by: Gurucharan Shetty <guru@ovn.org>

### CODE REVIEW

**Comment by rajatchopra** [comment]
@shettyg good catch.

Now mostly for my education here:
In the solution, is it assumed that there is a route to the gateway available?
e.g. what if this route was not available on the machine:
route add 172.16.1.1 dev eth0
simply because there is another default gateway through another interface.
Also, consequently the default route through this interface will not exist also. So, will our interface in the OVS bridge not have any gateway route?

**Comment by shettyg** [comment]
It is possible that we still are some corner case. But for your specific query.

>Now mostly for my education here:
>In the solution, is it assumed that there is a route to the gateway available?

The code gets the routes for only the interface for which we want to create a bridge. In this case, 3 looks like this in the routing table (even though we never specified 'eth0' in the command')

> 172.16.1.1 0.0.0.0  255.255.255.255 eth0

So we pick up that route too. 

If that route did not exist, and there was another default gateway, we simply would not have picked up that route.

>Also, consequently the default route through this interface will not exist also. So, will our interface in the OVS bridge not have any gateway route?

I _think_, there can only be one default gateway - i.e 0.0.0.0 route. If we have 2 interfaces, I would guess that the second interface would have a specific route which tells what is the next hop and will restore it.

**Comment by rajatchopra** [comment]
> If that route did not exist, and there was another default gateway, we simply would not have picked up that route.

Yes. That is clear.

> I think, there can only be one default gateway - i.e 0.0.0.0 route. If we have 2 interfaces, I would guess that the second interface would have a specific route which tells what is the next hop and will restore it.

But what will be the next hop route in OVS then? Or will we have none?

**Comment by shettyg** [comment]
>But what will be the next hop route in OVS then? Or will we have none?

The route for OVS bridge should be whatever the routes that existed for the physical interface. For OVN gateway, if you did not pass -gateway-nexthop as an option, it will chose the default gateway (which may work or may not work)

**Pull request merged**
