### PR TITLE
remove deadlock in network policy delete and pod watch

### PR DESCRIPTION
**Pull request by rajatchopra**
Three way deadlock:
1. Network policy delete
    Holds np.lock
    Issues <-stop that triggers RemovePodHandlers
    Waits on stopWg

2. Pod event delivered to policyPeerPodWatch
   Holds informer.Lock
   Waits on np.Lock to perform Pod event (although np is deleted already, but the check is done after acquiring the np lock)

3. Pod watch handler for the NP in question should be removed from federated handlers.
  Gets event on <- stop
  Calls RemovePodHandler
  Waits on informer.Lock that blocks stopWg.Done

@dcbw @shettyg PTAL

Signed-off-by: Rajat Chopra <rchopra@redhat.com>

### CODE REVIEW

**Comment by shettyg** [comment]
LGTM.

Couple of questions:

1. Were you planning to pursue https://github.com/openvswitch/ovn-kubernetes/pull/311 ? That would have negated this patch?

2. Over the long term, since we need to OVSDB via golang bindings, we will have to serialize all k8s events. So that is something to start thinking over soon too.

**Comment by dcbw** [comment]
@rajatchopra what if we got rid of np.deleted entirely, and instead just closed the NP's stop channel, waited for all the goroutines to stop, and *then* cleaned up the ingress/egress policies?

**Comment by rajatchopra** [comment]
@dcbw Yes that would work too. But we will have to still 'wait' with stopWg. #311 attempts to remove them all.
I am currently working on  #134, because that is blocking running the e2e network policy tests. I will get back to resolving this vs #311 after that work.

**Comment by shettyg** [comment]
Since this fixes a big bug, I think it makes sense to merge this and than do any better solutions.

**Pull request merged**
