### PR TITLE
go-controller: fold master/minion parts of ovn-k8s-overlay into ovn-kube

### PR DESCRIPTION
**Pull request by dcbw**
Instead of having ovnkube call out to ovn-k8s-overlay and
pass through a bunch of stuff it already knows, just call the Go code.

While we're there, we don't need to templatize the CNI config because
our CNI plugin doesn't care about any of the arguments, and it handles
IPAM internally rather than using the 'host-local' CNI plugin.

@rajatchopra @shettyg

### CODE REVIEW

**Comment by shettyg** [comment]
I did not test this, but overall it looks like a nice change. Did you test this? Can you please add Signed-off-by for each of your commits? LGTM.

**Comment by rajatchopra** [comment]
I tested this. The cluster comes up fine with basic connectivity checks working. Thanks Dan, this is a good cleanup.

**Comment by dcbw** [comment]
@shettyg I'll re-do the commit logs with signed-off-by and repush today.  Hopefully it can get merged then!

Yes, I tested it with openshift docker-in-docker and verified that an nginx pod comes up and that a service fronting that pod works as expected from a different node (by curling the LoadBalancer/External IP and service port).

**Comment by dcbw** [comment]
@shettyg @rajatchopra SOBs added and rebased on master.

**Pull request merged**
