### PR TITLE
Travis py35

### PR DESCRIPTION
**Pull request by salv-orlando**
Please do not review or merge yet.

### CODE REVIEW

**Comment by salv-orlando** [comment]
I also messed a bit this branch ;)

**Comment by salv-orlando** [comment]
This configuration should run 2 jobs - and for each job flake8 and the python tests for the appropriate version. I could not find a decent way to run 3 jobs: flake8, python2.7 and python 3.5

Obviously we can easily avoid running twice flake8
What bothers me is that from the tests I've been doing it appears that travisCI ignores env markers and ends up installing ovs 2.5 for the python 3.5 job.

If that's confirmed we either force ovs to 2.6.0-dev3 or wait for ovs 2.6 to be published to pypi (I think that will happen by the end of the week)

**Comment by russellb** [comment]
@salv-orlando I think the env marker support is a relatively new feature of pip.  travis-ci probably just doesn't have it.  :(

I'm responsible for getting ovs on pypi.  I'll get it done this week for sure.

**Comment by russellb** [comment]
..... annnnnd ovs 2.6.0 was just uploaded to pypi.

https://pypi.python.org/pypi/ovs/2.6.0

**Comment by salv-orlando** [comment]
thanks russellb!

Well maybe travisci supports env markers after all... I forgot to patch requirements.txt from the branch where I was doing unit tests.

**Pull request closed without merging**
