### PR TITLE
remove unnecessary go-routines around policy watches

### PR DESCRIPTION
**Pull request by rajatchopra**
With the addition of federated watch handlers, there are unnecessary go routines in the policy flow.
All we do with spinning a new go-routine for watching local peer pods for policy is 'add' the handlers and then wait for network policy to be removed so that we can 'remove' the handlers. We don't need go-routines for that.
This will be immensely helpful when we have 20k namespaces isolated from each other by at least as many NetworkPolicy objects.

Signed-off-by: Rajat Chopra <rchopra@redhat.com>

### CODE REVIEW

**Comment by rajatchopra** [comment]
@dcbw @shettyg 
This is a quick attempt and I have not reviewed/tested it myself. But please take a look nevertheless if its in the right direction. Thanks.

**Comment by dcbw** [comment]
@rajatchopra this approach looks good to me; haven't done in-depth review but I think you're on the right track

**Comment by rajatchopra** [comment]
Closing in favour of #413. Thanks Jacob.

**Pull request closed without merging**
