### PR TITLE
ovn-kube-cni-overlay.go: use client-go to communicate with api server

### PR DESCRIPTION
**Pull request by YaoZengzeng**

### CODE REVIEW

**Comment by shettyg** [comment]
Looks like linter found a styling issue..

**Comment by YaoZengzeng** [comment]
Updated @shettyg

**Comment by shettyg** [comment]
While doing https, the python CNI plugin, gets the API token from openvswitch database. See here: https://github.com/openvswitch/ovn-kubernetes/blob/master/ovn_k8s/common/kubernetes.py#L102

How does the golang code get it?

**Comment by YaoZengzeng** [comment]
@shettyg Golang code will also get API token from openvswitch database.Obviously, we can't pass the token to cni plugin as an argument.
In the future, it's better to connect to api server with https and use the way like ovnkube.go.Of course the difference is that we get "server, token, rootCAFile" from openvswitch database instead of commandline arugments.
Actually, I'm working on converting the ovn-k8s-gateway-helper to go, and I found it's more convenient to use client-go because of its watch mechanism.So this PR is just to test whether it's fine to use client-go like that.

**Comment by shettyg** [comment]
Okay. So, if I understand this right, the current golang CNI plugin code cannot do https, right? I am merging it anyway.

**Pull request merged**
