### PR TITLE
windows: Add gateway support

### PR DESCRIPTION
**Pull request by alinbalutoiu**
This patch separates the Linux specific code from the common
code inside gateway-init file. The code is moved in a helper
file.

Gateway init support is now enabled on Windows.

Signed-off-by: Alin-Gheorghe Balutoiu <alinbalutoiu@gmail.com>
Signed-off-by: Alin Gabriel Serdean <aserdean@ovn.org>
Co-authored-by: Alin Gabriel Serdean <aserdean@ovn.org>

### CODE REVIEW

**Comment by alinbalutoiu** [comment]
@rajatchopra @dcbw @shettyg can you please have a look over this? Thanks!

**Comment by aserdean** [comment]
Thanks for sending this up.

@dcbw and @shettyg can you PTAL to see if this the right direction of splitting the code?

**Comment by aserdean** [comment]
Yup it makes a lot of sense. I'll try an ansible run and add tested-by over the https://github.com/openvswitch/ovn-kubernetes/pull/465 if everything goes well.

**Comment by alinbalutoiu** [comment]
From a cluster with one master, one linux minion and one windows minion. Gateway running on both minion nodes:
```
$ curl 192.168.85.132:30714
<h1>This request was processed by container: nano-1803-win-dtb9rfu5o7n</h1>
$ curl 192.168.85.101:30714
<h1>This request was processed by container: nano-1803-win-dtb9rfu5o7n</h1>
$ curl 192.168.85.132:30714
Apache
$ curl 192.168.85.101:30714
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

**Comment by shettyg** [comment]
travis looks to be failing.

**Comment by aserdean** [comment]
```
root@master-linux:/home/ubuntu# ovn-nbctl list load-balancer
_uuid               : 1e6acf18-08f0-43c0-9d9d-cd51f4425042
external_ids        : {TCP_lb_gateway_router=GR_minion-linux}
name                : ""
protocol            : []
vips                : {"192.168.29.141:30376"="10.0.0.5:80,10.0.0.6:80,10.0.1.3:80"}

_uuid               : 017c230c-8425-40f1-8be2-a85f9085af08
external_ids        : {"k8s-cluster-lb-udp"=yes}
name                : ""
protocol            : udp
vips                : {"10.1.0.10:53"="10.0.0.4:53,10.0.0.7:53"}

_uuid               : 33720fdc-65d6-409a-b4f3-8a07816f0988
external_ids        : {"k8s-cluster-lb-tcp"=yes}
name                : ""
protocol            : tcp
vips                : {"10.1.0.10:53"="10.0.0.4:53,10.0.0.7:53", "10.1.0.1:443"="192.168.29.140:443", "10.1.0.204:8800"="10.0.0.5:80,10.0.0.6:80,10.0.1.3:80", "10.1.0.48:8800"="10.0.0.5:80,10.0.0.6:80,10.0.1.3:80"}

_uuid               : d4fd817f-5006-4731-9be3-692ab83ee271
external_ids        : {UDP_lb_gateway_router=GR_minion-linux}
name                : ""
protocol            : udp
vips                : {}

_uuid               : ce87a8e7-3d9d-4c84-b7c4-d8913bb07309
external_ids        : {UDP_lb_gateway_router="GR_win-dth15n6hkp9"}
name                : ""
protocol            : udp
vips                : {}

_uuid               : 9a1e5803-e091-464c-a2db-e0c99dbaeb4f
external_ids        : {TCP_lb_gateway_router="GR_win-dth15n6hkp9"}
name                : ""
protocol            : []
vips                : {"192.168.29.240:30376"="10.0.0.5:80,10.0.0.6:80,10.0.1.3:80"}
root@master-linux:/home/ubuntu# curl 192.168.29.240:30376
<h1>This request was processed by container: nano-1803-win-dth15n6hkp9</h1>
root@master-linux:/home/ubuntu# curl 192.168.29.240:30376
Apache
root@master-linux:/home/ubuntu# curl 192.168.29.240:30376
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
root@master-linux:/home/ubuntu# curl 192.168.29.141:30376
<h1>This request was processed by container: nano-1803-win-dth15n6hkp9</h1>
root@master-linux:/home/ubuntu# curl 192.168.29.141:30376
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
root@master-linux:/home/ubuntu# curl 192.168.29.141:30376
<h1>This request was processed by container: nano-1803-win-dth15n6hkp9</h1>
root@master-linux:/home/ubuntu# curl 192.168.29.141:30376
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
root@master-linux:/home/ubuntu#
```
Acked-by:  Alin Gabriel Serdean <aserdean@ovn.org>
Tested-by:  Alin Gabriel Serdean <aserdean@ovn.org>

@shettyg, @dcbw can you PTAL. Travis is also passing.

**Comment by shettyg** [comment]
Looks okay to me on linux side. I did not look at windows implementation. If @aserdean feels the latest code on windows is fine, please go ahead and merge.

**Pull request merged**
