### PR TITLE
Add config file for variables

### PR DESCRIPTION
**Pull request by alinbalutoiu**
Currently we are lacking a unified way to specify variables
defined by the user.

This patch adds the posibility to edit those variables which will
be stored inside a config file in /etc/ovn-kubernetes/ovn_k8s.conf

Signed-off-by: Alin Balutoiu <abalutoiu@cloudbasesolutions.com>

### CODE REVIEW

**Comment by shettyg** [comment]
Let us do this. I have a couple comments.

1. Let us put the config file in /etc/openvswitch instead of /etc/ovn-kubernetes. 
2. I would prefer the config.py to be in common/. Can we add this to common/config.py that already exists? 
3. There are a few unit tests that are failing that can be seen in the travis link above.

**Comment by alinbalutoiu** [comment]
Unfortunately when installing the package with pip you cannot specify an absolute path where you want to copy the config file. I have added a few more other locations where to search for the config file.
We will rely on an external script to copy the config file in /etc/openvswitch, which will be the first place where we search for the config file.
If not found there, we search in /usr/local/etc/openvswitch where pip should copy the config file. There is also a special case for the virtual env, where we search directly in the path from where the module was imported.
What do you think about this logic?

**Comment by shettyg** [comment]
I don't understand pip well. But the following diff installs it in /etc/openvswitch. Do you see a problem with that?

```
diff --git a/setup.cfg b/setup.cfg
index 3a1fe53..4f06c78 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -16,7 +16,7 @@ classifier =
 [files]
 packages = ovn_k8s
 data_files =
-    etc/openvswitch =
+    /etc/openvswitch =
         etc/ovn_k8s.conf
 scripts =
     bin/ovn-k8s-cni-overlay
```

**Comment by alinbalutoiu** [comment]
How did you install the package? I have tried your diff but when I do a ```pip install .``` from inside the repo it will install the config file in ```"/usr/local/lib/python2.7/dist-packages/etc/openvswitch/ovn_k8s.conf"``` and not in ```/etc/openvswitch/```

**Comment by shettyg** [comment]
>How did you install the package? I have tried your diff but when I do a pip install .

I did the same too on a Ubuntu 14.04 and Ubuntu 16.04. My pip version is 9.0.1.

**Comment by shettyg** [comment]
If you still see problems, I think we should just go ahead with /etc/ovn-kubernetes

**Comment by alinbalutoiu** [comment]
I have nothing against it if it works. I'm ok with the diff, we can go ahead with it.

**Comment by shettyg** [comment]
>I have nothing against it if it works. I'm ok with the diff, we can go ahead with it.

A concern is why it is not working at your end? May be the soln is not portable?  What is your environment details?

**Comment by alinbalutoiu** [comment]
I think I found out the issue on my end. If I am root and I do a ```pip install .``` inside the repo folder, it will copy the config file to ```/usr/local/lib/python2.7/dist-packages/etc/openvswitch/```. But if I do a ```sudo pip install .``` with a normal user, then it will copy it to ```/etc/openvswitch/```. It looks ok to me, we'll have to document it properly so the users will know what to do.

**Comment by shettyg** [comment]
If instead of /etc/openvswitch, we do /etc/ovn-kubernetes, does it always copy it there irrespective of using "sudo"?

**Comment by alinbalutoiu** [comment]
No, it's still the same as before from what I have seen in my tests, it doesn't matter the path that you put there.

**Comment by shettyg** [comment]
Lets go with this. Currently the commit has author as "Alin-Gheorghe Balutoiu" and Signed-off-by as "Alin Balutoiu". Can you re-push the commit fixing the discrepancy?

**Comment by alinbalutoiu** [comment]
Done.

**Pull request merged**
