### PR TITLE
ovnkube: Create gateways while doing minion-init.

### PR DESCRIPTION
**Pull request by shettyg**
This series creates a gateway via the 'node-init' command on ovnkube.
The general idea is to have the ability to create a gateway on every
minion atleast to rampout the local pod's initiated traffic via the same
node.  It also tries to make assumptions of the gateway interface to use
if one is not provided. The primary use case is to create gateways via
daemonsets.

### CODE REVIEW

**Comment by shettyg** [comment]
This is ready for review. This series fixes a few issues with the existing code too. The fixes are part of separate commits.

**Comment by shettyg** [comment]
@rajatchopra Were you planning to look at this?

**Comment by shettyg** [comment]
>I presume this code will not do the prep work if option#2 is desired. And we still need the gateway-helper utility.

This only does 2.  It will convert your nic (e.g eth0) to breth0. It will move eth0's ip address and routes to breth0. It will then create a patch port between breth0 and br-int.

My idea was to enhance this in the next patch series to

1. To also program breth0 to handle only egress traffic. i.e traffic initiated from pods will go through this and come back.
2. Have the ability in ovnkube to optionally not program nodeports. With this, we don't need gateway helper to mux/demux tarffic.

**Comment by shettyg** [comment]
The vagrant patch has the example on how to use it:
https://github.com/openvswitch/ovn-kubernetes/pull/209/files#diff-cf436ce63c459d330daad9f08a1fd4c6R67

**Comment by rajatchopra** [comment]
What if I need option#1? I want to avoid NicsToBridge.

**Comment by shettyg** [comment]
>What if I need option#1? I want to avoid NicsToBridge.

You still use "ovn-k8s-overlay gateway-init" for the time being. And then enhance the ability to do the same via node-init code. It should just be an extra option passed. I did not want to expand the scope for review/testing drastically.

**Comment by shettyg** [comment]
I have another patch series which will add option 1. But that series includes some other involved changes too, so don't want to mix that with this series. With this series, things continue to work the same way as before - but we also have some extra options.

Once this goes in, I will send the next one for review.

**Comment by shettyg** [comment]
Thanks for the review. I sent https://github.com/openvswitch/ovn-kubernetes/pull/214 to handle option 1 discussed here.

**Pull request merged**
