### PR TITLE
vagrant: Support use of vagrant-libvirt.

### PR DESCRIPTION
**Pull request by russellb**
I got this to where VMs will start using vagrant-libvirt, but I haven't verified that it's all working properly.  I figured I'd at least share what I have so far.

### CODE REVIEW

**Comment by shettyg** [comment]
LGTM.

**Comment by russellb** [comment]
Thanks, I'll apply this to master

**Comment by shettyg** [comment]
@russellb 

On my mac, it downloads ceph/ubuntu-xenial too. I wonder why?

**Comment by shettyg** [comment]
The following diff helps on mac side. Will it be a problem for libvirt?

```
diff --git a/vagrant/Vagrantfile b/vagrant/Vagrantfile
index 595f13f..89dbc52 100644
--- a/vagrant/Vagrantfile
+++ b/vagrant/Vagrantfile
@@ -9,7 +9,7 @@ vagrant_config = YAML.load_file("provisioning/vm_config.conf.yml")
 Vagrant.configure(2) do |config|
   config.vm.box = "ubuntu/xenial64"
   config.vm.provider "libvirt" do |lv, override|
-    config.vm.box = "ceph/ubuntu-xenial"
+    override.vm.box = "ceph/ubuntu-xenial"
     lv.driver = "kvm"
   end
```

**Comment by russellb** [comment]
I'd go ahead and apply your fix.  I don't want to cause any regressions for virtualbox support.  I'll keep hacking on libvirt support and submit more patches if needed.

Maybe I should also let you test changes before I apply them in the future.  :-)

**Pull request merged**
