### PR TITLE
endpoints: ignore empty addresses and ports

### PR DESCRIPTION
**Pull request by dcbw**
Apparently there are cases where some endpoint subsets won't have
addresses filled in, or the port is 0.  kube-proxy's iptables backend has done this since late 2015.

@rajatchopra @shettyg @danwinship @squeed

### CODE REVIEW

**Comment by danwinship** [comment]
> Apparently there are cases where some endpoint subsets won't have
> addresses filled in, or the port is 0

[citation required]

`k8s.io/kubernetes/pkg/apis/core/validation/validation.go:ValidateEndpoints()` prohibits both of those.

**Comment by dcbw** [comment]
```
2018-12-03T21:47:54.283Z|00711|ovn_northd|WARN|Dropped 107 log messages in last 16 seconds (most recently, 8 seconds ago) due to excessive rate
2018-12-03T21:47:54.283Z|00712|ovn_northd|WARN|bad ip address or port for load balancer key None:9093
```

But fair enough, looks like the validation code has existed longer than the kube-proxy code that double-checks the IP:port pair, which was added as:

```
		portsToEndpoints := map[string][]hostPortPair{}
		for i := range svcEndpoints.Subsets {
			ss := &svcEndpoints.Subsets[i]
			for i := range ss.Ports {
				port := &ss.Ports[i]
				for i := range ss.Addresses {
					addr := &ss.Addresses[i]
					portsToEndpoints[port.Name] = append(portsToEndpoints[port.Name], hostPortPair{addr.IP, port.Port})
				}
			}
		}

		for portname := range portsToEndpoints {
			svcPort := proxy.ServicePortName{NamespacedName: types.NamespacedName{Namespace: svcEndpoints.Namespace, Name: svcEndpoints.Name}, Port: portname}
			curEndpoints := proxier.endpointsMap[svcPort]
			newEndpoints := flattenValidEndpoints(portsToEndpoints[portname])
			if len(curEndpoints) != len(newEndpoints) || !slicesEquiv(slice.CopyStrings(curEndpoints), newEndpoints) {
				glog.V(1).Infof("Setting endpoints for %q to %+v", svcPort, newEndpoints)
				proxier.endpointsMap[svcPort] = newEndpoints
			}
			activeEndpoints[svcPort] = true
		}

func isValidEndpoint(hpp *hostPortPair) bool {
	return hpp.host != "" && hpp.port > 0
}

func flattenValidEndpoints(endpoints []hostPortPair) []string {
	// Convert Endpoint objects into strings for easier use later.
	var result []string
	for i := range endpoints {
		hpp := &endpoints[i]
		if isValidEndpoint(hpp) {
			result = append(result, net.JoinHostPort(hpp.host, strconv.Itoa(hpp.port)))
		} else {
			glog.Warningf("got invalid endpoint: %+v", *hpp)
		}
	}
	return result
}
```

by commit ae569e20b53d9d in August 2015. Perhaps that caught some empty bits after

**Comment by shettyg** [comment]
I did not look deeply, but do check when service is deleted to make sure that the VIP gets deleted. Currently empty endpoints is how we decide to delete service VIP.

**Comment by danwinship** [comment]
> 2018-12-03T21:47:54.283Z|00712|ovn_northd|WARN|bad ip address or port for load balancer key None:9093

Ah, no, that's not an empty endpoint IP address, that's a service with a `ClusterIP` that is literally the string `"None"`, which is to say, a headless service. We do need to filter those out, but that's on the service side, not the endpoints side.

**Comment by dcbw** [comment]
@danwinship ah ok, good catch. I tried to see if that was Service or Endpoints and couldn't follow the northd code far enough.

**Pull request closed without merging**
