### PR TITLE
ClusterRoleBinding is OpenShift

### PR DESCRIPTION
**Pull request by pecameron**
Changed ovn-policy.yaml to reflect that.

Signed-off-by: Phil Cameron <pcameron@redhat.com>

### CODE REVIEW

**Comment by pecameron** [comment]
@squeed @rajatchopra @dcbw PTAL

**Comment by dcbw** [comment]
@pecameron Hmm, when I did the apiVersion bits to use rbac.authorization.k8s.io/v1 I was looking at https://kubernetes.io/docs/reference/access-authn-authz/rbac/ which indicates that ClusterRoleBinding is also a Kubernetes thing.  What errors were you getting when you tried this with OpenShift Phil?

**Comment by pecameron** [comment]
@dcbw 
The ClusterRoleBinding "ovn-cluster-reader" is invalid: roleRef.kind: Unsupported value: "": supported values: "ClusterRole"
----
authorization.openshift.io/v1 works

**Comment by pecameron** [comment]
@dcbw @rajatchopra At present ovn does not install because of this problem. PTAL

**Comment by dcbw** [comment]
@pecameron per your comment in https://github.com/openvswitch/ovn-kubernetes/pull/435 we should close this PR, right?

**Comment by pecameron** [comment]
Used 435 instead of this pr

**Pull request closed without merging**
