### PR TITLE
docs: add switch-per-node architecture diagram

### PR DESCRIPTION
**Pull request by dcbw**
Signed-off-by: Dan Williams <dcbw@redhat.com>

@shettyg @rajatchopra @putnopvut

### CODE REVIEW

**Comment by dcbw** [comment]
@shettyg does this look more or less correct?  PDF version is http://people.redhat.com/dcbw/switch-per-node.pdf

**Comment by shettyg** [comment]
@dcbw 
Yeah. It looks close to correct. One error is that the mgmt port IP address is the second IP address of the subnet.

**Comment by dcbw** [comment]
@shettyg updated both ODG and the PDF

**Comment by shettyg** [comment]
How do you view this file generally? Github doesn't show it.

**Comment by dcbw** [comment]
@shettyg it's an OpenOffice/LibreOffice document, so Google Docs or LibreOffice should show it.  I can save it as EPS or SVG if you'd like too.

**Pull request merged**
