### PR TITLE
travis-ci: Add travis-ci config that runs tox.

### PR DESCRIPTION
**Pull request by russellb**
Signed-off-by: Russell Bryant <russell@ovn.org>

### CODE REVIEW

**Comment by russellb** [comment]
I tested this by configuring travis-ci to run against my fork of this repo.

**Comment by shettyg** [comment]
LGTM. I did not test this, but we will soon find out.

**Comment by salv-orlando** [comment]
Thanks a lot!

**Comment by russellb** [comment]
@shettyg I don't have access to enable travis-ci on the repo. It looks like someone with admin access has to do it.

**Comment by blp** [comment]
I just enabled ovn-kubernetes over at the travis-ci webpage. Let me know if I need to do anything else.

**Pull request merged**
