### PR TITLE
docs: update switch-per-node diagram to include gateway details and PDF version

### PR DESCRIPTION
**Pull request by dcbw**
@shettyg @rajatchopra

### CODE REVIEW

**Comment by shettyg** [comment]
Do we need all 3? Should we delete the odg one?

**Comment by dcbw** [comment]
@shettyg the ODG should probably be the source if we need to update it in the future.  I removed the SVG one, and instead posted a PDF one which is easier to view I think.

**Comment by shettyg** [comment]
@dcbw 

I still see the svg one.

**Comment by dcbw** [comment]
@shettyg fixed

**Pull request merged**
