### PR TITLE
Read and use config file in CNI plugin

### PR DESCRIPTION
**Pull request by dcbw**
@shettyg @rajatchopra @alinbalutoiu 

Windows MTU hookup not done, but the value is plumbed through to helper_windows.go.

### CODE REVIEW

**Comment by shettyg** [comment]
@dcbw 

The vagrant fails. I get the following error:
>FATA[0000] failed to open config file /etc/openvswitch/ovn_k8s.conf: open /etc/openvswitch/ovn_k8s.conf: no such file or directory

**Comment by shettyg** [comment]
Looks like pods are not getting created. Likely a bug in the CNI plugin

**Comment by shettyg** [comment]
@dcbw Yeah.

**Comment by alinbalutoiu** [comment]
It might be the same on Linux, but on Windows kubelet prints this when creating the POD:
>E0518 06:26:43.461289     968 cni.go:259] Error adding network: failed to open config file : open : The system cannot find the file specified.
E0518 06:26:43.461289     968 cni_windows.go:49] error while adding to cni network: failed to open config file : open : The system cannot find the file specified.
W0518 06:26:43.465145     968 docker_sandbox.go:353] failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod "nano-1709_default": failed to open config file : open : The system cannot find the file specified.

**Comment by dcbw** [comment]
@alinbalutoiu @shettyg took a bit longer to get back to this one than I thought, but re-pushed and verified with vagrant.

**Comment by shettyg** [comment]
It does feel a little convoluted in initConfig with 3 different ways of configFile, but I can't think right away of a better way to do this.

**Pull request merged**
