### PR TITLE
ovnkube.log and ovnkube-master.log shouldn’t be in /var/log/openvswitch

### PR DESCRIPTION
**Pull request by winsopc**
Signed-off-by: Zhen Wang <zhewang@nvidia.com>

### CODE REVIEW

**Comment by shettyg** [comment]
Do we need instructions to create that directory? Should we add the creation of directory inside ovnkube?

**Comment by girishmg** [comment]
@shettyg Good catch. I  think we should create that log directory from within ovkube. This will be required when not using daemonsets.

**Comment by winsopc** [comment]
@shettyg Thanks for reviewing my code.I agree with you that we should take care of logdir creation.
Since ovnkube take -logfile to specify the log directory location. I want to add the code in config.go.
Let me know your thought.

diff --git a/go-controller/pkg/config/config.go b/go-controller/pkg/config/config.go
index 4c8ba930..fd3529a2 100644
--- a/go-controller/pkg/config/config.go
+++ b/go-controller/pkg/config/config.go
@@ -593,6 +593,12 @@ func InitConfigWithPath(ctx *cli.Context, exec kexec.Interface, configFile strin
        logrus.SetLevel(logrus.Level(Logging.Level))
        if Logging.File != "" {
                var file *os.File
+               if _, err = os.Stat(filepath.Dir(Logging.File)); os.IsNotExist(err) {
+                       dir := filepath.Dir(Logging.File)
+                       if err = os.MkdirAll(dir, 0660); err != nil {
+                               logrus.Errorf("failed to create logfile directory %s (%v). Ignoring..", dir, err)
+                       }
+               }
                file, err = os.OpenFile(Logging.File, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0660)
                if err != nil {
                        logrus.Errorf("failed to open logfile %s (%v). Ignoring..", Logging.File, err)

**Comment by winsopc** [comment]
@shettyg Thanks for the comments,  I just updated the code to address your comments.
Please take a look when you have time.

**Comment by girishmg** [comment]
LGTM, so +1

**Pull request merged**
