### PR TITLE
Provide LICENSE file

### PR DESCRIPTION
**Pull request by pecameron**
This is the apache 2.0 license.

Signed-off-by: Phil Cameron <pcameron@redhat.com>

### CODE REVIEW

**Comment by pecameron** [comment]
@shettyg @girishmg @dcbw @squeed @JacobTanenbaum 
ovn-kubernetes needs an open source license. We do a lot of development, including OpenShift and kubernetes, under Apache 2.0 so I copied that license here. If we don't want that license lets get a discussion going and settle on a license.

**Comment by shettyg** [comment]
@pecameron 

https://github.com/openvswitch/ovn-kubernetes/blob/master/COPYING

**Comment by pecameron** [comment]
@shettyg 
Is it OK to have a copy of the Apache 2.0 license here? Most repos have an explicit LICENSE file.

**Comment by shettyg** [comment]
@pecameron 

Duplicate files result in confusion and staleness. You can remove COPYING file.

**Comment by pecameron** [comment]
@shettyg I am setting up a new openshift/ovn-kubernetes repo for openshift specific work mostly related to the openshift related build environment. In the process, the lack of a LICENSE file was noted. The current openvswitch/ovn-kubernetes is the upstream of this repo so general development will continue there. This is all part of getting ovn into Openshift 4.1

**Comment by shettyg** [comment]
@pecameron Sure. You can remove COPYING file.

**Comment by pecameron** [comment]
@shettyg I removed COPYING. Are any further changes needed?

**Pull request merged**
