### PR TITLE
contrib: Add ansible playbooks to deploy kubernetes

### PR DESCRIPTION
**Pull request by alinbalutoiu**
This patch adds some ansible playbooks which deploy a kubernetes
cluster. It also adds Windows Server minion nodes to the cluster.

More details can be found in the README.md from contrib folder.

Signed-off-by: Alin Balutoiu <abalutoiu@cloudbasesolutions.com>
Signed-off-by: Alin Gabriel Serdean <aserdean@ovn.org>
Co-authored-by: Alin Gabriel Serdean <aserdean@ovn.org>

### CODE REVIEW

**Comment by alinbalutoiu** [comment]
There is a small README.md file inside contrib folder added by this PR. That should help if someone wants to try this out.

**Comment by alinbalutoiu** [comment]
@rajatchopra PR is ready for merge
cc: @aserdean

**Comment by aserdean** [comment]
Acked-by: Alin Gabriel Serdean <aserdean@ovn.org>

**Comment by alinbalutoiu** [comment]
Hi @rajatchopra , have you changed any of the defaults variables? (kubernetes version etc.) Can you check the output of the services running on the master node? It seems like there is an error with kube-apiserver.

**Comment by rajatchopra** [comment]
@alinbalutoiu Thanks for this amazing work.

**Pull request merged**
