### PR TITLE
Add overlay diagram to README.md

### PR DESCRIPTION
**Pull request by RostyslavFridman**
Signed-off-by: Rostyslav Fridman rostyslav_fridman@epam.com

### CODE REVIEW

**Comment by shettyg** [comment]
Thanks for working on this.

I think it may be helpful if you change the wording from "NAT 10.x.x.0/16" to "SNAT to eth IP address". On the same lines, change "NAT services to endpoints" to "DNAT services to endpoints".

I think the 2 lines connecting "OVS" to "K8s switch" and "External switch" is a little confusing. What were you trying to express out there?

**Comment by shettyg** [comment]
It may also help if you add multiple "K8s switch" connected to router (as we created one per host). And for each switch, you can have a mgmt interface and multiple pods connected.  And remove the connection from OVS to OVN block, that way we keep the logical topology seperate.

**Comment by RostyslavFridman** [comment]
Good point about NAT. I renamed these lines.
Regarding the lines connecting OVS to OVN, I was trying to show IP flow.
It might be clearer if the flow lines are named:
http://i.imgur.com/qRki95i.png

**Comment by shettyg** [comment]
>Regarding the lines connecting OVS to OVN, I was trying to show IP flow.
It might be clearer if the flow lines are named:

Instead of getting those lines from OVS block, how about a different colored line that starts before the pod interface and external interface joins the OVS block and name those colored lines as "logical connections".

**Comment by RostyslavFridman** [comment]
Updated the diagram to this one: https://i.imgur.com/i7sci9O.png

**Comment by shettyg** [comment]
Thanks, merged.

**Pull request merged**
